//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "parts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub part_catalog_id: Uuid,
    pub product_id: Option<Uuid>,
    pub serial_number: String,
    pub part_condition_id: i32,
    pub manufactured_date: DateTimeUtc,
    pub installation_date: Option<DateTimeUtc>,
    pub removal_date: Option<DateTimeUtc>,
    pub scrapped_date: Option<DateTimeUtc>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::part_catalog::Entity",
        from = "Column::PartCatalogId",
        to = "super::part_catalog::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    PartCatalog,
    #[sea_orm(has_many = "super::part_changes::Entity")]
    PartChanges,
    #[sea_orm(
        belongs_to = "super::part_conditions::Entity",
        from = "Column::PartConditionId",
        to = "super::part_conditions::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    PartConditions,
    #[sea_orm(has_many = "super::part_image_links::Entity")]
    PartImageLinks,
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Products,
}

impl Related<super::part_catalog::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PartCatalog.def()
    }
}

impl Related<super::part_changes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PartChanges.def()
    }
}

impl Related<super::part_conditions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PartConditions.def()
    }
}

impl Related<super::part_image_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PartImageLinks.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl Related<super::images::Entity> for Entity {
    fn to() -> RelationDef {
        super::part_image_links::Relation::Images.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::part_image_links::Relation::Parts.def().rev())
    }
}

impl Related<super::work_order_closing_forms::Entity> for Entity {
    fn to() -> RelationDef {
        super::part_changes::Relation::WorkOrderClosingForms.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::part_changes::Relation::Parts.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
