//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "parts_by_model")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub part_catalog_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub product_model_code: String,
    pub quantity: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::part_catalog::Entity",
        from = "Column::PartCatalogId",
        to = "super::part_catalog::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    PartCatalog,
    #[sea_orm(
        belongs_to = "super::product_models::Entity",
        from = "Column::ProductModelCode",
        to = "super::product_models::Column::ModelCode",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    ProductModels,
}

impl Related<super::part_catalog::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PartCatalog.def()
    }
}

impl Related<super::product_models::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductModels.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
