//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "part_types")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub part_type_name: String,
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::new_part_forms::Entity")]
    NewPartForms,
    #[sea_orm(has_many = "super::part_catalog::Entity")]
    PartCatalog,
}

impl Related<super::new_part_forms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NewPartForms.def()
    }
}

impl Related<super::part_catalog::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PartCatalog.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
