//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "part_catalog")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub part_number: String,
    pub part_types_id: i32,
    pub mfg_number: String,
    pub description: Option<String>,
    pub part_mfg_status: i32,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::part_catalog_image_links::Entity")]
    PartCatalogImageLinks,
    #[sea_orm(
        belongs_to = "super::part_mfg_statuses::Entity",
        from = "Column::PartMfgStatus",
        to = "super::part_mfg_statuses::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    PartMfgStatuses,
    #[sea_orm(
        belongs_to = "super::part_types::Entity",
        from = "Column::PartTypesId",
        to = "super::part_types::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    PartTypes,
    #[sea_orm(has_many = "super::parts::Entity")]
    Parts,
    #[sea_orm(has_many = "super::parts_by_model::Entity")]
    PartsByModel,
}

impl Related<super::part_catalog_image_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PartCatalogImageLinks.def()
    }
}

impl Related<super::part_mfg_statuses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PartMfgStatuses.def()
    }
}

impl Related<super::part_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PartTypes.def()
    }
}

impl Related<super::parts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Parts.def()
    }
}

impl Related<super::parts_by_model::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PartsByModel.def()
    }
}

impl Related<super::images::Entity> for Entity {
    fn to() -> RelationDef {
        super::part_catalog_image_links::Relation::Images.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::part_catalog_image_links::Relation::PartCatalog
                .def()
                .rev(),
        )
    }
}

impl Related<super::product_models::Entity> for Entity {
    fn to() -> RelationDef {
        super::parts_by_model::Relation::ProductModels.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::parts_by_model::Relation::PartCatalog.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
