//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Serialize, Deserialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub account_status: i32,
    pub role_id: i32,
    #[sea_orm(unique)]
    pub email: String,
    pub full_name: String,
    pub password_hash: String,
    pub phone_number: String,
    pub province: Option<String>,
    pub fcm_token: Option<String>,
    pub installation_id: Option<String>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account_status::Entity",
        from = "Column::AccountStatus",
        to = "super::account_status::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    AccountStatus,
    #[sea_orm(has_many = "super::products::Entity")]
    Products,
    #[sea_orm(
        belongs_to = "super::roles::Entity",
        from = "Column::RoleId",
        to = "super::roles::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Roles,
    #[sea_orm(has_many = "super::sessions::Entity")]
    Sessions,
    #[sea_orm(has_many = "super::warranties::Entity")]
    Warranties,
    #[sea_orm(has_many = "super::work_order_reject_forms::Entity")]
    WorkOrderRejectForms,
    #[sea_orm(has_many = "super::work_order_state_history::Entity")]
    WorkOrderStateHistory,
}

impl Related<super::account_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountStatus.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Roles.def()
    }
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl Related<super::warranties::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Warranties.def()
    }
}

impl Related<super::work_order_reject_forms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkOrderRejectForms.def()
    }
}

impl Related<super::work_order_state_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkOrderStateHistory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
